//! litany-core: domain types and recurrence engine.
//!
//! Design invariants (TechGodHQ doctrine):
//! - Pure domain logic lives here; no HTTP, no Telegram, no provider code.
//! - Surfaces (CLI/HTTP/MCP) are generated by hydra from `api/operations.yaml`.
//! - Every completed occurrence records its actual completion timestamp;
//!   streaks are derived, never stored counters.

pub mod model;
pub mod recurrence;

pub use model::{Occurrence, Recurrence, Task};
pub use recurrence::next_due;
